TraceCondition:
  Command: /home/alient/Codes/eunomia-bpf-examples/ioctl-hook/ioctl_bug
  Sudo: True
  NoExec: True
  LogsDir: ./tracer_logs
  ScriptPath: ./script.bt
  Targets:
  - FilePath: /lib/x86_64-linux-gnu/libc.so.6
    Functions:
      - Func: ioctl
        HookType: uprobe
        Triggers:
          - arg2 == 0x541c
          - auto arg1 arg2
  - FilePath: /lib/x86_64-linux-gnu/libcrypto.so.3
    Functions:
      - Func: EVP_EncryptUpdate
        HookType: uprobe
        Triggers:
          - arg4 >= 64 && arg4 <= 1024
          - auto arg4 arg5
      - Func: EVP_EncryptFinal_ex
        HookType: uprobe
        Triggers:
          - arg2 > 0 && arg2 <= 1024
          - auto arg1
          # - cpu
          # - disk
